vhdl_parser/src/source.rs
vhdl_parser/src/tokenizer.rs

I've squashed the work I was doing into a single commit in a new branch, and so am creating a new pull request.
The work to get the source comments into tokens is done.
I haven't started on moving the comments from the tokens to the AST, but I think the token work should be merged so that it's not a pain to keep it consistent with master.
I'll keep the old pull request open for the continuing work on getting the comments into the AST.

Add source comments to tokens.

---

vhdl_parser/src/analysis/semantic.rs
vhdl_parser/src/ast/mod.rs
vhdl_parser/src/attributes.rs

Fixes #31.
Happy to assign copyright to the project owner.

Add constant and type entity class in attribute specifications

---

.github/workflows/build-test-all.yml

Work towards #47.
Currently builds and tests both projects on Linux and Windows. Probably needs caching to make it faster.

Create GitHub CI configuration to build and test

---

vhdl_libraries/synopsys/std_logic_arith.vhdl
vhdl_libraries/synopsys/std_logic_signed.vhdl
vhdl_libraries/synopsys/std_logic_unsigned.vhdl
vhdl_libraries/vhdl_ls.toml
vhdl_libraries/vital2000/memory_b.vhdl
vhdl_libraries/vital2000/memory_p.vhdl
vhdl_libraries/vital2000/prmtvs_b.vhdl
vhdl_libraries/vital2000/prmtvs_p.vhdl
vhdl_libraries/vital2000/timing_b.vhdl
vhdl_libraries/vital2000/timing_p.vhdl

This pull requests adds the Synopsys `std_logic_arith`, `std_logic_unsigned` and `std_logic_signed` packages, and the VITAL 2000 packages.
Resolves #55

Add Synopsys and VITAL 2000 packages

---

.github/workflows/crates-io.yml
.github/workflows/docker.yml

Skip publish for forked repos

---

.dockerignore
Dockerfile

Fixes #65.
This is untested as I don't have Docker on this machine. @mbrobbel are you able to review and test this?

Update docker build to use built-in libraries

---

vhdl_lang/src/analysis/lock.rs
vhdl_lang/src/analysis/named_entity.rs
vhdl_lang/src/analysis/root.rs
vhdl_lang/src/ast.rs
vhdl_lang/src/ast/any_design_unit.rs
vhdl_lang/src/data/source.rs
vhdl_lang/src/data/symbol_table.rs
vhdl_lang/src/syntax/tokens/tokenizer.rs

Add code documentation

---

vhdl_lang/src/project.rs
vhdl_lang/src/syntax/concurrent_statement.rs
vhdl_lang/src/syntax/design_unit.rs
vhdl_ls/src/vhdl_server.rs

Check for postponed at end of process

---

vhdl_lang/src/config.rs
vhdl_lang/src/data/source.rs
vhdl_lang/src/data/symbol_table.rs
vhdl_libraries/synopsys/std_logic_misc.vhdl
vhdl_ls/src/main.rs
vhdl_ls/src/rpc_channel.rs
vhdl_ls/src/stdio_server.rs
vhdl_ls/src/vhdl_server.rs

Add std_logic_misc package to built in libraries

Add std_logic_misc package

---

vhdl_lang/src/project.rs
vhdl_ls/src/rpc_channel.rs
vhdl_ls/src/stdio_server.rs
vhdl_ls/src/vhdl_server.rs

If supported by the client, the server registers for changes to the configuration file using client/registerCapability.
When the configuration file changes, the client send a notification workspace/didChangeWatchedFiles to the server. The configuration is then loaded again and project configuration is updated:
The design state is reset, new files are added and parsed. As required for incremental document updates, source files that are already loaded are parsed from in-memory sources.
This closes #41

Reload design when workspace configuration changes

---

vhdl_lang/src/ast/search.rs

There were a few places in the AST search code that used the following pattern:
```rust
return_if_found!(searcher.search_with_pos(&self.pos).or_not_found());
```
However, `search_with_pos` returns `NotFinished` to continue searching of the region, or `Finished(NotFound)` if the position does not match. Both cases result in `NotFound`, so the above statement has no effect.
I assume this was meant to abort the search if `self.pos` does not include the position being searched for, as it does in other parts of the search code using the following pattern:
```rust
searcher.search_with_pos(&self.pos).or_else(|| { ...
```
I believe this (actually useful) pattern should be applied to the problematic cases as well - ergo this PR.

Fix short-circuiting of searches with search_with_pos.

---

vhdl_lang/src/ast/search.rs

Refactor all occurrences of the following pattern:
```rust
searcher.search_with_pos(&self.pos).or_else(|| { ... })
```
into:
```rust
return_if_finished!(searcher.search_with_pos(&self.pos));
...
```
in search.
This affects both the performance fixes in cf23bde956617b750aa3a2282d958cd71f8cf06b, as well as other occurrences where `or_else` was being used.

Refactor search_with_pos short-circuiting by returning early

---

.gitmodules
example_project/README.md
example_project/setup.sh

I've left them at the same commit as `setup.sh` script currently references.

Use submodules for example_project

---

.github/workflows/crates-io.yml
.github/workflows/docker.yml

Update conditional actions after repo move.
Fixes #128

Fix action publish paths

---

vhdl_lang/src/analysis/completion.rs
vhdl_lang/src/analysis/declarative.rs
vhdl_lang/src/analysis/tests/visibility.rs
vhdl_lang/src/ast.rs
vhdl_lang/src/ast/search.rs
vhdl_lang/src/ast/visitor.rs
vhdl_lang/src/syntax/subprogram.rs
vhdl_lang/src/syntax/test.rs
vhdl_lang/src/syntax/tokens/tokenizer.rs

Closes #191, closes #154 
Now parses and analyzes the examples correctly.

Parse subprogram header and parameter keyword

---

vhdl_lang/src/analysis/declarative.rs
vhdl_lang/src/analysis/named_entity.rs
vhdl_lang/src/analysis/overloaded.rs
vhdl_lang/src/ast.rs
vhdl_lang/src/ast/display.rs
vhdl_lang/src/ast/search.rs
vhdl_lang/src/ast/visitor.rs
vhdl_lang/src/syntax/subprogram.rs
vhdl_lang/src/syntax/test.rs

This PR only considers the syntactic parsing.
Analysis will come in a separate PR

Parse Subprogram Instantiation Statement

---

vhdl_lang/src/analysis/completion.rs

Enables completions for package instances and enables function and types for generic maps

Implement completions for package instances

---

vhdl_lang/src/config.rs

Disallow a library being called 'work'

---

vhdl_lang/src/analysis/assignment.rs
vhdl_lang/src/analysis/association.rs
vhdl_lang/src/analysis/concurrent.rs
vhdl_lang/src/analysis/sequential.rs
vhdl_lang/src/ast.rs
vhdl_lang/src/ast/search.rs
vhdl_lang/src/lib.rs
vhdl_lang/src/main.rs
vhdl_lang/src/named_entity/arena.rs
vhdl_lang/src/syntax/concurrent_statement.rs
vhdl_lang/src/syntax/names.rs

There are some legacy clippy ignores that should probably no longer be ignored

Remove unneeded clippy lints

---

vhdl_lang/src/analysis/concurrent.rs
vhdl_lang/src/analysis/declarative.rs
vhdl_lang/src/analysis/design_unit.rs
vhdl_lang/src/analysis/names.rs
vhdl_lang/src/analysis/package_instance.rs
vhdl_lang/src/analysis/root.rs
vhdl_lang/src/analysis/sequential.rs
vhdl_lang/src/analysis/standard.rs
vhdl_lang/src/analysis/subprogram.rs
vhdl_lang/src/analysis/tests/hierarchy.rs
vhdl_lang/src/analysis/tests/mod.rs
vhdl_lang/src/analysis/types.rs
vhdl_lang/src/ast.rs
vhdl_lang/src/ast/search.rs
vhdl_lang/src/named_entity.rs
vhdl_lang/src/named_entity/arena.rs
vhdl_lang/src/named_entity/types.rs
vhdl_lang/src/project.rs
vhdl_lang/src/syntax/tokens/tokenizer.rs
vhdl_ls/src/vhdl_server.rs

Add token span to Symbol Documentation

---

vhdl_lang/src/completion.rs
vhdl_ls/src/vhdl_server.rs

As suggested in a comment in #164 also adds architectures to the list of completion items if there is more than one architecture for an entity

Add architectures to entity completion

---

vhdl_lang/src/analysis/design_unit.rs
vhdl_lang/src/analysis/tests/package_instance.rs

Closes #271
This was a regression issue caused by #248

Fix: Also consider InterfacePackageInstances in use clauses

---

Cargo.lock
README.md
vhdl_lang/Cargo.toml
vhdl_lang/src/config.rs

Also replace the custom implementation with [subst](https://docs.rs/subst/latest/subst/)
Fixes #278

Temporary Fix: Do not substitute environment variables on windows

---

vhdl_lang/src/syntax/component_declaration.rs
vhdl_lang/src/syntax/interface_declaration.rs

parse constructs that are easy to support
- Allow trailing semicolons on interface lists
- second `component` keyword is optional for component declarations

Simple VHDL2019 constructs

---

vhdl_lang/src/completion.rs
vhdl_lang/src/named_entity/design.rs

Add signal and port declarations to the list of completion items

---

vhdl_lang/src/completion.rs
vhdl_lang/src/completion/entity_instantiation.rs
vhdl_lang/src/completion/generic.rs
vhdl_lang/src/completion/region.rs
vhdl_lang/src/completion/selected.rs
vhdl_ls/src/vhdl_server/completion.rs

Closes #164 
With the recent additions and improvements to completions, component instantiations are now supported

Enable component instantiations

---

vhdl_lang/src/analysis/declarative.rs
vhdl_lang/src/analysis/tests/view_declarations.rs

Analyze mode view elements

---

README.md
vhdl_lang/src/syntax/tokens/tokenizer.rs

Conditionally enable tokenizing

---

vhdl_lang/src/analysis/association.rs
vhdl_lang/src/analysis/concurrent.rs
vhdl_lang/src/analysis/declarative.rs
vhdl_lang/src/analysis/overloaded.rs
vhdl_lang/src/analysis/package_instance.rs
vhdl_lang/src/analysis/semantic.rs
vhdl_lang/src/analysis/standard.rs
vhdl_lang/src/analysis/subprogram.rs
vhdl_lang/src/analysis/tests/association_formal.rs
vhdl_lang/src/analysis/tests/package_instance.rs
vhdl_lang/src/analysis/tests/resolves_design_units.rs
vhdl_lang/src/analysis/tests/resolves_names.rs
vhdl_lang/src/analysis/types.rs
vhdl_lang/src/named_entity.rs
vhdl_lang/src/named_entity/design.rs
vhdl_lang/src/named_entity/file.rs
vhdl_lang/src/named_entity/formal_region.rs
vhdl_lang/src/named_entity/object.rs
vhdl_lang/src/named_entity/overloaded.rs
vhdl_lang/src/named_entity/region.rs
vhdl_lang/src/named_entity/types.rs

Refactor map aspects
