VHDL-LS/rust_hdl

- .dockerignore
- .travis.yml
- Dockerfile
This PR adds [Clippy](https://github.com/rust-lang-nursery/rust-clippy) (ignore exit code for now) and [rustfmt](https://github.com/rust-lang-nursery/rustfmt) to the Travis build script.
It also adds a Dockerfile to build small executable images of the binary crates. This allows easy usage of the project:
```bash
docker run -it --rm -v `pwd`:/src rust_hdl/vhdl_parser --show /src/file.vhd
```
I also modified the Travis file to cache cargo dependencies, to build against both stable and nightly rust, and to build the crates in separate jobs.
> Add clippy, rustfmt, dockerfile and update Travis

- Dockerfile
This removes the default `--help` command from the Dockerfile to allow easy usage of the language server.
It allows people with docker installed to use the published image to run the language server.
> Update Dockerfile to allow easy usage of language server

- vhdl_ls/src/stdio_server.rs
- vhdl_ls/src/vhdl_server.rs
This adds the shutdown method and exit notification to the language server to prevent errors when using this with a client which use this method and notification to stop the server.
Can you please review? I'm not sure if this correctly stops the spawned threads and closes the channels.
> Add shutdown method and exit notification to language server

- vhdl_ls/Cargo.toml
- vhdl_ls/src/lib.rs
- vhdl_ls/src/main.rs
- vhdl_ls/src/stdio_server.rs
This adds `log` and `env_logger` to the `vhdl_ls` crate. This allows users to disable output when preferred (e.g. Atom logs `stderr` message in the console, currently resulting in all the debug messages ending up there).
> Add env_logger to vhdl_ls

- vhdl_parser/src/main.rs
At least this makes sure that the version listed there is up-to-date.
> Use cargo environment variables in clap app

- vhdl_parser/src/tokenizer.rs
The function `parse_real_literal()` now also correctly parses real literals such as 2.5E+3. A corresponding test case has been added.
In addition, the '+' in the exponent is only skipped if it is not preceeded by a '-'.
This fixes the parsing of reals reported in issue #36.
> Fix `parse_real_literal` to accept capital 'E' for exponent

- Dockerfile
This PR was triggered by a comment by @Bochlin in Gitter which stated a problem with the current Docker image. It uses a relative path for the application, which prevents users from setting a different working directory. This modification allows running the containers with different workdirs.
> Use absolute path in Dockerfile 

- .github/workflows/build-test-all.yml
This pull request updates the github workflow to use a matrix strategy consisting of build targets and rust versions.
Targets:
- x86_64-unknown-linux-gnu
- x86_64-pc-windows-msvc
Rust versions:
- stable
- 1.40.0 (Minimum Supported Rust Version)
rustfmt is run on Rust stable for x86_64-unknown-linux-gnu  
clippy is run on Rust stable and MSRV for x86_64-unknown-linux-gnu
> Update workflow to use matrix and add MSRV build

- .github/workflows/build-test-all.yml
- vhdl_ls/Cargo.toml
- vhdl_parser/Cargo.toml
- vhdl_parser/src/config.rs
From #45:
> I refactored the configuration loading to make it easy to add loading of installed configuration: See: https://github.com/kraigher/rust_hdl/blob/master/vhdl_parser/src/config.rs#L236-L239
> You only need to add a `load_installed_config` there to implement it.
I've implemented this function. I'm only up to chapter 5 in the Rust book, so improvements are welcome!
I've not added any tests. Am I right in thinking there's none for the other configuration loading functions either? I'm also couldn't work out how you add tests for whether a feature flag is enabled or not anyway.
> I think we should use the `cfg!` macro or attribute to set the relative path to the installed `vhdl_ls.toml` file. By default it think the relative path should assume the binary ends up in `target/release` …
> Add loading of packaged libraries by feature flag

- .dockerignore
- .github/workflows/docker.yml
- .travis.yml
This moves the Docker image build and deploy workflow to Github Actions. This workflow runs for pushed tags and pushes to master (the image with the `latest` tag).
I removed the Docker build and deploy steps from Travis.
@kraigher you'll have to set the `DOCKER_USERNAME` and `DOCKER_PASSWORD` secrets for this to work.
> Move Docker image build and deploy to Github Action workflow

- vhdl_lang/src/analysis/sequential.rs
- vhdl_lang/src/ast.rs
- vhdl_lang/src/ast/search.rs
- vhdl_lang/src/syntax/sequential_statement.rs
- vhdl_lang/src/syntax/tokens/tokenizer.rs
Work in progress to add matching case statement.
Added tokenization of '?' and updated parsing of case statement to support matching case.
```
case? expr is
when "--00" => null;
when others => null;
end case?;
```
This update removes the error thrown by the parser but does not store in the AST that it is a matching case statement. My suggestion is to add a `is_matching: bool` element to the `ast::Selection` struct.
@kraigher Any comments?
> Add matching case

- .github/workflows/crates-io.yml
- .github/workflows/docker.yml
Currently `Docker` action fails on pushing to forked repos (`Crates.io` would also fail on a publishig a tag). This adds a check on the actions so that they only act on the main repo to stop actions failing in forks.
> Allow publish actions only from main repo

- vhdl_lang/src/analysis/concurrent.rs
- vhdl_lang/src/analysis/tests/resolves_names.rs
- vhdl_lang/src/ast.rs
- vhdl_lang/src/syntax/concurrent_statement.rs
Updates for `block_statement`:
- Parsing and analysis of `block_header`
- Fix error when optional `is` is used after `guard_condition`
- Analysis of `guard_condition`
> Add block_header and analyze guard_condition

- vhdl_lang/src/ast.rs
- vhdl_lang/src/syntax/names.rs
Fixes parsing error when multiple "up-levels" are present in external name e.g.  
`<< signal ^.^.^.dut.gen(0) : std_logic >>`  
The number of up-levels are not stored and a TODO comment is added. The number up up-levels are required if elaboration checks are implemented as the hierarchy of the design must be known.
> Allow multiple '^' in relative external name

- vhdl_ls/Cargo.toml
- vhdl_ls/src/main.rs
For the release process it would be good to be able to check the version of the `vhdl_ls` binary.
At the moment the language server crashes with any command line arguments:
```
>target\debug\vhdl_ls.exe --version
thread '<unnamed>' panicked at 'explicit panic', vhdl_ls\src\stdio_server.rs:192:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
This uses `clap` like `vhdl_lang`.
> Add version info to vhdl_ls

- .github/workflows/build-test-all.yml
I finally have a release process that works! There's an example release created by the same YAML file (in a different branch) at [Xcodo/rust_hdl/releases/tag/v0.0.0](https://github.com/Xcodo/rust_hdl/releases/tag/v0.0.0).
I'm not totally happy, but it turns out writing a CI process by snatching half an hour here and there is very inefficient so probably best for other people to make suggestions! @kraigher @Bochlin? Also happy to explain what's going on and add comments if we need it.
Things I don't like
- The workflow runs twice when you push - once for the commit to the branch and once for the tag.
- The tag workflow builds against MSRV when it doesn't need to. Could add more conditionals to the build steps or have a separate release workflow.
- There's a lot of uploading and downloading …
> GitHub release process

- vhdl_libraries/synopsys/std_logic_misc.vhdl
`std_logic_misc` is written for VHDL 93 and several functions have overloaded variants for std_logic_vector and std_ulogic_vector. Since in VHDL 2008, `std_logic_vector` is a resolved subtype of `std_ulogic_vector` the signatures are the same.
> Comment out std_logic_vector functions from std_logic_misc.

- .github/workflows/build-test-all.yml
- vhdl_lang/src/analysis/lock.rs
- vhdl_lang/src/analysis/root.rs
- vhdl_lang/src/analysis/tests/incremental_analysis.rs
- vhdl_lang/src/analysis/tests/resolves_design_units.rs
- vhdl_lang/src/analysis/tests/resolves_type_mark.rs
- vhdl_lang/src/analysis/tests/util.rs
- vhdl_lang/src/config.rs
- vhdl_lang/src/data/contents.rs
- vhdl_lang/src/data/source.rs
- vhdl_lang/src/syntax/attributes.rs
- vhdl_lang/src/syntax/design_unit.rs
- vhdl_lang/src/syntax/expression.rs
- vhdl_lang/src/syntax/names.rs
- vhdl_lang/src/syntax/subtype_indication.rs
- vhdl_lang/src/syntax/test.rs
- vhdl_lang/src/syntax/tokens/tokenizer.rs
- vhdl_lang/src/syntax/type_declaration.rs
- vhdl_ls/src/rpc_channel.rs
- vhdl_ls/src/vhdl_server.rs
I recently started to familiarize myself with the project and noticed that Clippy on the current stable Rust reports some warnings.
This PR should fix all of them and also enable Clippy checks for tests and non-default crate features (`--all-targets --all-features`) in GitHub build/test workflow.
> Fix Clippy for current stable Rust (1.45.2)

- vhdl_ls/Cargo.toml
- vhdl_ls/src/stdio_server.rs
- vhdl_ls/src/vhdl_server.rs
While working on "reload on config file change", I needed a way to send [`client/registerCapability`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#client_registerCapability) requests from the server to the client to register for [`workspace/didChangeWatchedFiles`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_didChangeWatchedFiles) notifications for the config file. But as far as I could figure out, [`jsonrpc_core`](https://crates.io/crates/jsonrpc-core) currently does not support handling incoming responses from the client (that occur after sending a request).
Taking a look at the RPC implementation of [`rust-analyzer`](https://github.com/rust-analyzer/rust-analyzer/) for reference, I …
> Use lsp-server crate for RPC channel handling

- vhdl_lang/src/syntax/declarative_part.rs
- vhdl_lang/src/syntax/interface_declaration.rs
The "pure" keyword was previously added to the tokenizer only.
Extending the syntax parser with "Pure" where "Impure" was used allows for parsing explicit pure functions correctly.
This closes #92.
> Add explicit "pure" to the syntax parser

- release_notes/v0.16.0.md
- vhdl_lang/Cargo.toml
- vhdl_ls/Cargo.toml
It would be great to do a release to make the improvements added available easily.
I've created release notes and updated the packages. A tag will need to be created by you @kraigher if you'd be able to do that (I can't do that in a pull request). Thanks a lot for keeping the admin going.
> Prepare for v0.16.0 release

- vhdl_lang/src/analysis/root.rs
- vhdl_lang/src/ast.rs
- vhdl_lang/src/ast/display.rs
- vhdl_lang/src/ast/search.rs
- vhdl_lang/src/project.rs
- vhdl_lang/src/syntax/expression.rs
- vhdl_lang/src/syntax/interface_declaration.rs
- vhdl_lang/src/syntax/test.rs
- vhdl_ls/src/stdio_server.rs
- vhdl_ls/src/vhdl_server.rs
As discussed in chat, this series of commits adds support for textDocument/hover to show information about declaration nodes through the language server.
I was careful to implement hover using as much of the available infrastructure as possible, specifically the AST-traversal implemented via the Search trait. This is accomplished by replacing `Searcher::search_decl_pos` with `Searcher::search_decl`, which takes an additional enum variant (`FoundDeclaration`) with a reference back to the actual declaration node. The default implementation of `search_decl` simply calls `search_decl_pos` in order to be backwards compatible.
The most work was needed to implement the Display trait for the declarative AST types. Most types are formatted such that they are compatible with the associated parse …
> Implement language server textDocument/hover

- .github/workflows/build-test-all.yml
- Dockerfile
- vhdl_lang/Cargo.toml
- vhdl_lang/src/config.rs
- vhdl_ls/Cargo.toml
As discussed in #136, I removed the "packaged" feature and instead search in hardcoded places for the installed vhdl libraries. The current list looks like that:
```rust
let search_paths = [
"/usr/lib/rust_hdl/vhdl_libraries",
"../vhdl_libraries",
"../../vhdl_libraries",
];
```
Since I'm new to rust I would appreciate some comments on the code.
> Search the installed libraries in a hardcoded set of locations

- vhdl_lang/src/analysis.rs
- vhdl_lang/src/analysis/literals.rs
- vhdl_lang/src/analysis/region.rs
- vhdl_lang/src/analysis/standard.rs
- vhdl_lang/src/analysis/static_expression.rs
- vhdl_lang/src/analysis/tests/typecheck_expression.rs
- vhdl_lang/src/data/source.rs
Analyze `BitString`s and report when they are not setup correctly.
```vhdl
constant v: bit_vector := 2SX""; -- Cannot expand an empty signed bit string
constant w: bit_vector := X"10G"; -- type 'BIT' does not define character 'G'
constant x: bit_vector := D"1AFFE"; -- Illegal digit 'A' for base 10
constant z: bit_vector := 8SX"0FF"; -- Truncating to 8 bit would loose information
```
I want to start collaborating on this project as I am currently using and enjoying it. This project fills an important gap for us HDL developers, so thank you for making this Open Source.
> Analyze bit strings

- vhdl_lang/src/analysis/concurrent.rs
- vhdl_lang/src/analysis/formal_region.rs
- vhdl_lang/src/analysis/tests/homographs.rs
Closes #182 
Implementation detail:
The labels were still defined in the old scope (i.e. `define_labels_for_concurrent_part` was called with the non-nested scope)
> Fix: Allow components with the same name in different blocks

- Cargo.lock
- vhdl_lang/src/analysis/expression.rs
- vhdl_lang/src/analysis/formal_region.rs
- vhdl_lang/src/analysis/names.rs
Closes #184 
Implementation details:
Introduces a new return type `AttrResolveResult` which is either a type (for attributes such as `'subtype`, `'element`) or a value (for most other attributes such as `'high`, `'low`, ...)
Based on this attribute the name can be resolved correctly and `a'subtype'high` will resolve to the correct type while `a'subtype` as an expression yields an error
> Feat: Enable type attributes

- vhdl_ls/src/stdio_server.rs
I noticed in an example in rust-analyzer repository: https://github.com/rust-lang/rust-analyzer/blob/master/lib/lsp-server/examples/goto_def.rs#L86C31-L86C46 that there is a handle_shutdown method that does a little more than what vhdl_ls currently did. Using this method also fixes #194 thanks to not actually deserializing the request - so it kind of works around the problem, so probably not the best solution.
It looks like the parameters of the shutdown request that are sent are: `{}`, this gets parsed into Map instead of unit - `()`.
> Shutdown the server on `shutdown` request using `connection.handle_shutdown`.

- vhdl_lang/src/analysis/concurrent.rs
- vhdl_lang/src/analysis/design_unit.rs
- vhdl_lang/src/analysis/named_entity.rs
- vhdl_lang/src/analysis/package_instance.rs
- vhdl_lang/src/ast.rs
- vhdl_lang/src/ast/display.rs
- vhdl_lang/src/ast/search.rs
- vhdl_lang/src/syntax/concurrent_statement.rs
- vhdl_lang/src/syntax/context.rs
- vhdl_lang/src/syntax/declarative_part.rs
- vhdl_lang/src/syntax/expression.rs
- vhdl_lang/src/syntax/interface_declaration.rs
- vhdl_lang/src/syntax/names.rs
- vhdl_lang/src/syntax/range.rs
- vhdl_lang/src/syntax/separated_list.rs
- vhdl_lang/src/syntax/test.rs
Relates to #201 
Refactor the following:
- `Vec<AssociationElement>` to `SeparatedList<AssociationElement>`
- Some cases of `Vec<AssociationElement>` to `MapAspect`
Both changes are performed to record the position of the tokens in an easier way.
> Refactor: Vector of AssociationElements to MapAspect

- vhdl_lang/src/ast.rs
- vhdl_lang/src/syntax/concurrent_statement.rs
- vhdl_lang/src/syntax/configuration.rs
- vhdl_lang/src/syntax/context.rs
- vhdl_lang/src/syntax/declarative_part.rs
- vhdl_lang/src/syntax/design_unit.rs
- vhdl_lang/src/syntax/interface_declaration.rs
- vhdl_lang/src/syntax/names.rs
- vhdl_lang/src/syntax/separated_list.rs
- vhdl_lang/src/syntax/test.rs
- vhdl_lang/src/syntax/tokens/tokenstream.rs
Improve the following diagnostics for map aspects:
- Empty association list (generic map or port map): Now "Association list cannot be empty"
- Trailing comma: Same error message but parsing goes on
- Extraneous commas (i.e. `port map (a => a,, b => b)`): Now "extraneous comma"
This also enables better completions as the parser can parse more semantically incorrect code.
> Improve diagnostics for map aspects

- vhdl_lang/src/analysis/completion.rs
As was suggested, simplify the extraction method by removing the visitor and replacing it with the `AnyEntKind::Component` and `AnyEntKind::Design` values.
Also seems to fix the issue where completion options aren't shown when the declaration is in a separate file.
> Simplify the completion generics and port extraction method

- vhdl_lang/src/analysis.rs
- vhdl_lang/src/analysis/root.rs
- vhdl_lang/src/completion.rs
- vhdl_lang/src/lib.rs
- vhdl_lang/src/project.rs
As discussed in the chat, `completion` was moved out of the `analysis` mod and is now its own module.
> Refactor: Move completion to its own module

- README.md
Add examples for wildcards/glob patterns and `is_third_party` setting in TOML file.
I think it's good to aid discoverability for these features, especially as common libraries like UVVM have many unused signals.
I can make the examples more generic if you prefer, but this one may also help some people understand how to support Xilinx libraries.
> Extend TOML example

- vhdl_lang/src/syntax/design_unit.rs
- vhdl_lang/src/syntax/interface_declaration.rs
- vhdl_lang/src/syntax/names.rs
Small PR. Improve the quality of error messages and disallow interface lists to be empty.
According to the reference manual:
```
interface_list ::= interface_element { ; interface_element }
```
so an interface list must hold at least one element. Therefore declarations of the following form:
```vhdl
function foo() return bar;
```
are illegal in VHDL. This PR adds an appropriate error message.
Also improves the error message of function calls such as 
```
foo()
```
Previously, the error message was `expected {expression}`, now it's `Association list cannot be empty`
> Disallow Interface lists to be empty

- vhdl_lang/src/analysis/root.rs
- vhdl_lang/src/analysis/tests/hierarchy.rs
Hi, I've extended the find_implementation function to also search for architectures which implement an entity.
> extend goto/implementation to find architectures of entities

- vhdl_lang/src/analysis/concurrent.rs
- vhdl_lang/src/analysis/declarative.rs
- vhdl_lang/src/analysis/design_unit.rs
- vhdl_lang/src/analysis/expression.rs
- vhdl_lang/src/analysis/names.rs
- vhdl_lang/src/analysis/package_instance.rs
- vhdl_lang/src/analysis/range.rs
- vhdl_lang/src/analysis/semantic.rs
- vhdl_lang/src/analysis/subprogram.rs
- vhdl_lang/src/analysis/types.rs
Towards #147
Also simplifies  some functions because the error handling is now more consistent
When a `TypeMark` can be parsed as a name (or a derivative of a name), the relevant functions now return an `EvalResult` instead of an `AnalysisResult`.
> Refactor: More EvalResults and less AnalysisResults

- vhdl_lang/src/analysis/concurrent.rs
- vhdl_lang/src/analysis/declarative.rs
- vhdl_lang/src/analysis/design_unit.rs
- vhdl_lang/src/analysis/names.rs
- vhdl_lang/src/analysis/package_instance.rs
- vhdl_lang/src/analysis/semantic.rs
- vhdl_lang/src/analysis/tests/resolves_names.rs
- vhdl_lang/src/analysis/tests/resolves_type_mark.rs
- vhdl_lang/src/ast.rs
- vhdl_lang/src/ast/display.rs
- vhdl_lang/src/ast/search.rs
- vhdl_lang/src/ast/util.rs
- vhdl_lang/src/completion.rs
- vhdl_lang/src/named_entity/region.rs
- vhdl_lang/src/syntax/concurrent_statement.rs
- vhdl_lang/src/syntax/configuration.rs
- vhdl_lang/src/syntax/declarative_part.rs
- vhdl_lang/src/syntax/expression.rs
- vhdl_lang/src/syntax/interface_declaration.rs
- vhdl_lang/src/syntax/names.rs
- vhdl_lang/src/syntax/subtype_indication.rs
- vhdl_lang/src/syntax/test.rs
Closes #147 
This removes the `SelectedName` enum. Analysis now only considers "regular" names. When only selected names are allowed in the specification, the parser still only considers selected names, but returns a regular name.
This simplifies the analyzer and removes duplication.
This has no measurable performance impact (tested using `cargo bench`)
> Replace selected name with name

- vhdl_lang/src/analysis/declarative.rs
- vhdl_lang/src/analysis/tests/custom_attributes.rs
- vhdl_lang/src/analysis/tests/declarations.rs
Closes #242 
@kraigher is this the desired behavior? See the test below that I had to alter. Was setting `myattr` to `signal` instead of `entity` intentional?
> Publish better diagnostic for attributes

- vhdl_lang/src/data/contents.rs
Hello, it's been quite some time. I am _reopening_ (creating a new one instead since it seems I don't have permission to reopen PRs here) #197.
One possible way to resolve https://github.com/VHDL-LS/rust_hdl/issues/193.
lsp-mode in emacs sometimes tries to edit something past end of line if other conditions are met. Specifically, the template system coming with vhdl-mode seems to trigger this behavior. This removes \n from one of the lines, making rust_hdl contents and actual file contents different.
I have added a unit test to go past the end of line. It indeed fails without the lines I added, and works with them. I also found a bug in my code thanks to running the unit tests. The last line had \n added as well, although it shouldn't. I added a condition for that.
If you know of a better …
>  Return \n to end of line in case it's deleted

- README.md
This language server can be easily configured for Emacs also through the [`vhdl-ext`](https://github.com/gmlarumbe/vhdl-ext/) extension package.
It supports Emacs builtin `eglot` client as well as `lsp-mode`.
> Update Emacs config section in README.md

- vhdl_lang/src/analysis/concurrent.rs
- vhdl_lang/src/analysis/root.rs
- vhdl_lang/src/ast.rs
- vhdl_lang/src/ast/search.rs
- vhdl_lang/src/completion.rs
- vhdl_lang/src/data/source.rs
- vhdl_lang/src/lib.rs
- vhdl_lang/src/named_entity/region.rs
- vhdl_lang/src/named_entity/visibility.rs
- vhdl_lang/src/syntax/concurrent_statement.rs
- vhdl_lang/src/syntax/design_unit.rs
- vhdl_lang/src/syntax/tokens/tokenizer.rs
- vhdl_ls/src/vhdl_server.rs
Towards #164 
Unsure whether this closes 164, but this is a big steps towards it. This PR implements entity completion. What's still missing is
- showing components for instantiation
- ~enabling completing components and entities from other libraries (currently, everything is completed using the `work` library)~
- ~Limiting the scope. Currently, all visible entities are brought into scope~
There are also some other changes here (like adding the `TokenSpan` attributes to some statements) that I implemented but no longer need. However, these changes are beneficial anyway so I kept them. Hope this doesn't blow up the PR too much.
In theory, this PR is ready for review but I'll still keep it as draft since I want to add a couple of tests and comments.
Happy to receive feedback from anyone …
> Entity Completion

- vhdl_lang/src/analysis/association.rs
- vhdl_lang/src/analysis/tests/assignment_typecheck.rs
- vhdl_lang/src/named_entity.rs
- vhdl_lang/src/named_entity/formal_region.rs
In VHDL, when a subprogram is declared with a parameter list that is not `constant` (i.e., the implicit default), the actual part must be a name denoting that subprogram. So, for example, a procedure `proc` that is defined as follows:
```vhdl
procedure proc(signal foo: foo_type; variable bar: bar_type);
```
can only be called using
```vhdl
proc(actual_foo, actual_bar);
```
where `actual_foo` denotes a signal and `actual_bar` denotes a variable or shared variable. This PR adds checks for this behaviour.
Relevant LRM section: 4.2.2.1
> Check the interface mode of a subprograms interface list

- vhdl_ls/src/vhdl_server.rs
At the moment, when there is an error with the `vhdl_ls.toml` config file (e.g., the file is bad formatted or there is the `work` library name present), the language server will show something like "Library mapping is unknown due to missing vhdl_ls.toml config file ...".
This error message makes it seem like there is no `vhdl_ls.toml` file present eve though there is. I hope to add a better description of when something is wrong with the file which is not related to the file being missing with this PR.
> Change the error message when the error is something other than NotFound

- vhdl_lang/src/config.rs
Quick fix to support local installations, first and foremost [Mason](https://github.com/williamboman/mason.nvim)
There's a relevant issue open on their registry repo: https://github.com/mason-org/mason-registry/issues/3615
I added `../share/vhdl_libraries` for now, but I can also imagine adding an environment variable as well, if that'd be useful.
> feat: search standard libs in `../share/`

- vhdl_lang/src/config.rs
Fixes #174.
I've tested this PR in the VSCode plugin using the Language Server User Path, and it works great for me.
> Substitute environment variables into config paths

- vhdl_lang/src/analysis/analyze.rs
- vhdl_lang/src/analysis/association.rs
- vhdl_lang/src/analysis/concurrent.rs
- vhdl_lang/src/analysis/design_unit.rs
- vhdl_lang/src/analysis/expression.rs
- vhdl_lang/src/analysis/names.rs
- vhdl_lang/src/analysis/range.rs
Finally remove the `AnalysisResult` in favour of the `EvalResult`.
This makes the code more readable and more maintainable. Further additions to the analysis do not have to worry about what kind of result to return and simply return an `EvalResult`.
This also adds some documentation to the `Result`'s
> Remove analysis result

- vhdl_lang/src/analysis/association.rs
- vhdl_lang/src/analysis/tests/assignment_typecheck.rs
The following snippet was incorrectly marked as erroneous:
```vhdl
procedure tee(
file     file_handle : text;
variable my_line     : inout line
) is
variable v_line : line;
begin
write(v_line, my_line.all);
writeline(file_handle, v_line);
end procedure tee;
```
with the error message "Name must denote a file name".
The procedure `writeline` is from the standard library.
This fixes this behaviour by also checking whether the file is an `AnyEntKind::InterfaceFile`
> Fix: Recognize file name as file

- README.md
[Issue#266](https://github.com/VHDL-LS/rust_hdl/issues/266#issue-2164238029)
> added "Use in Neovim" to readme

- README.md
This is addressing [issue#113](https://github.com/VHDL-LS/rust_hdl/issues/113), which is quite old, but it came up in another issue recently. So I guess it makes sense to leave a little hint when installing VHDL_LS from crate.
> added hint about vhdl_libraries directory when installing from crates.io

- README.md
Adds instructions to use [`nvim-lspconfig`](https://github.com/neovim/nvim-lspconfig) for the LSP client. `nvim-lspconfig` has a built in [configuration](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/vhdl_ls.lua) that works for `vhdl_ls`.
I also changed the heading type of the `Configuration` section that discusses the TOML file, since it was `###` which effectively put it in the neovim section, when it's actually common.
> Adds more info for configuring Neovim's LSP client for VHDL_LS

- README.md
- vhdl_lang/src/config.rs
See #278
Now also allows variable substitution in Windows using the `%VAR_NAME%` syntax
> Implement variable substitution for Windows machines

- vhdl_lang/src/syntax/alias_declaration.rs
- vhdl_lang/src/syntax/attributes.rs
- vhdl_lang/src/syntax/common.rs
- vhdl_lang/src/syntax/component_declaration.rs
- vhdl_lang/src/syntax/concurrent_statement.rs
- vhdl_lang/src/syntax/configuration.rs
- vhdl_lang/src/syntax/context.rs
- vhdl_lang/src/syntax/declarative_part.rs
- vhdl_lang/src/syntax/design_unit.rs
- vhdl_lang/src/syntax/expression.rs
- vhdl_lang/src/syntax/interface_declaration.rs
- vhdl_lang/src/syntax/names.rs
- vhdl_lang/src/syntax/object_declaration.rs
- vhdl_lang/src/syntax/parser.rs
- vhdl_lang/src/syntax/range.rs
- vhdl_lang/src/syntax/separated_list.rs
- vhdl_lang/src/syntax/sequential_statement.rs
- vhdl_lang/src/syntax/subprogram.rs
- vhdl_lang/src/syntax/subtype_indication.rs
- vhdl_lang/src/syntax/test.rs
- vhdl_lang/src/syntax/tokens/tokenstream.rs
- vhdl_lang/src/syntax/type_declaration.rs
- vhdl_lang/src/syntax/waveform.rs
Adds a `ParsingContext` to all parsing related functions instead of manually passing `TokenStream`s and potentially `DiagnosticHandler`s to the individual functions.
This is helpful for future expansions e.g., for more lax parsing, to have the `DiagnosticHandler` ready or to pass a `VHDLStandard` to the individual functions without having to drill the argument all the way down to functions down in the stack.
> Add parsing context

- vhdl_ls/src/main.rs
- vhdl_ls/src/vhdl_server.rs
This adds the initial configuration and closes #172 
The new configuration will be found (and must be set) in the Language Server Client configuration.
An additional desirable feature is that the project could be added and parsed only (without analysis) to show syntax errors only. However, this is not part of this PR but may be implemented at a later stage.
> Enable ignoring files that are not part of the project

- vhdl_lang/src/analysis/root.rs
- vhdl_lang/src/named_entity/arena.rs
- vhdl_lang/src/project.rs
- vhdl_ls/src/vhdl_server.rs
Closes #300 
While this might not be the final / ideal solution, checks that a raw entity id points to a valid entity reference before returning it.
This handles situations gracefully where raw entity IDs are used to pass information.
> Check raw entity IDs from an LSP client

- Cargo.lock
- vhdl_lang/Cargo.toml
- vhdl_lang/src/config.rs
- vhdl_lang/src/main.rs
- vhdl_lang/tests/integration_tests.rs
- vhdl_lang/tests/unused_declarations/my_entity.vhd
- vhdl_lang/tests/unused_declarations/vhdl_ls.toml
- vhdl_ls/src/vhdl_server.rs
Closes #291
- The `vhdl_lang` executable now checks for unused declarations.
- Some arguments were removed from the executable as there are better options (i.e., benchmarking for the `perf` or `bench` option)
- Add integration test
Additionally, `vhdl_ls` will exit with exit code '1', when there are any errors found in the executable.
> Refactor vhdl lang main

- vhdl_lang/src/analysis/root.rs
- vhdl_lang/src/project.rs
- vhdl_ls/src/stdio_server.rs
- vhdl_ls/src/vhdl_server.rs
Hi, thank you all for the great project, which has helped me a lot while writing VHDL code!
In most of the other language servers, I use a lot the `documentHighlight` feature, which highlights all the occurrences of a symbol in the current file. Noticing that it was missing from this LS I attempted my own implementation
See the result here:
https://github.com/VHDL-LS/rust_hdl/assets/10487071/ebb064ce-89f1-459c-a37b-edf11d7af977
It seems that VScode has some kind of fallback that performs the same result even if the server does not have this capability! (I am actually using another editor - Zed - that would not do the same)
See the before and after in Zed:
https://github.com/VHDL-LS/rust_hdl/assets/10487071/6162dcfc-965a-4857-86e5-8dc6a060a4f0 …
> Add support for textDocument/documentHighlight request

- vhdl_ls/src/vhdl_server.rs
- vhdl_ls/src/vhdl_server/completion.rs
- vhdl_ls/src/vhdl_server/lifecycle.rs
- vhdl_ls/src/vhdl_server/rename.rs
- vhdl_ls/src/vhdl_server/text_document.rs
- vhdl_ls/src/vhdl_server/workspace.rs
Restructure the language server (`language_server.rs`) into a module with sub-modules that contain specialised code (i.e., for rename, diagnostics, e.t.c.)
> Restructure the language server

- Cargo.lock
- vhdl_ls/Cargo.toml
- vhdl_ls/src/vhdl_server.rs
- vhdl_ls/src/vhdl_server/workspace.rs
Closes #234
This now uses a fuzzy matcher to detect which result to include, and which to omit.
> Improve quality of workspace symbols

- vhdl_lang/src/analysis/declarative.rs
- vhdl_lang/src/analysis/design_unit.rs
- vhdl_lang/src/analysis/expression.rs
- vhdl_lang/src/analysis/literals.rs
- vhdl_lang/src/analysis/names.rs
- vhdl_lang/src/analysis/package_instance.rs
- vhdl_lang/src/analysis/range.rs
- vhdl_lang/src/analysis/semantic.rs
- vhdl_lang/src/analysis/subprogram.rs
- vhdl_lang/src/analysis/tests/assignment_typecheck.rs
- vhdl_lang/src/analysis/tests/context_clause.rs
- vhdl_lang/src/analysis/tests/custom_attributes.rs
- vhdl_lang/src/analysis/tests/package_instance.rs
- vhdl_lang/src/analysis/tests/resolves_names.rs
- vhdl_lang/src/analysis/tests/resolves_type_mark.rs
- vhdl_lang/src/analysis/tests/subprogram_arguments.rs
- vhdl_lang/src/analysis/tests/subprogram_instance.rs
- vhdl_lang/src/analysis/tests/typecheck_expression.rs
- vhdl_lang/src/analysis/tests/view_declarations.rs
- vhdl_lang/src/analysis/types.rs
- vhdl_lang/src/ast.rs
- vhdl_lang/src/ast/display.rs
- vhdl_lang/src/ast/search.rs
- vhdl_lang/src/data/error_codes.rs
- vhdl_lang/src/named_entity/types.rs
- vhdl_lang/src/syntax/expression.rs
- vhdl_lang/src/syntax/names.rs
- vhdl_lang/src/syntax/test.rs
This simplifies the AST and removes obsolete code, for example for `Searcher` and `Display` implementation. Parsing is unaffected, some error messages might be slightly different after this change.
> Simplify analysis for `TypeMark` with analysis for `Name`

- vhdl_lang/src/analysis/assignment.rs
- vhdl_lang/src/analysis/concurrent.rs
- vhdl_lang/src/analysis/expression.rs
- vhdl_lang/src/analysis/sequential.rs
- vhdl_lang/src/analysis/tests/typecheck_expression.rs
- vhdl_lang/src/ast.rs
- vhdl_lang/src/ast/search.rs
- vhdl_lang/src/completion.rs
- vhdl_lang/src/completion/generic.rs
- vhdl_lang/src/syntax/concurrent_statement.rs
- vhdl_lang/src/syntax/sequential_statement.rs
* Closes #317 
* Simplifies and canonicalises AST of waveform assignments
* Enables completions from within subprograms
* Remove completions after ';' token
> Miscellaneous improvements

- vhdl_lang/src/analysis/analyze.rs
- vhdl_lang/src/analysis/declarative.rs
- vhdl_lang/src/analysis/design_unit.rs
- vhdl_lang/src/analysis/sequential.rs
- vhdl_lang/src/analysis/subprogram.rs
- vhdl_lang/src/analysis/types.rs
- vhdl_lang/src/ast.rs
- vhdl_lang/src/ast/display.rs
- vhdl_lang/src/ast/search.rs
- vhdl_lang/src/completion/generic.rs
- vhdl_lang/src/completion/map_aspect.rs
- vhdl_lang/src/named_entity.rs
- vhdl_lang/src/syntax/declarative_part.rs
- vhdl_lang/src/syntax/interface_declaration.rs
- vhdl_lang/src/syntax/object_declaration.rs
- vhdl_lang/src/syntax/recover.rs
- vhdl_lang/src/syntax/test.rs
- vhdl_lang/src/syntax/type_declaration.rs
For example, the declaration
```vhdl
signal a, b : std_logic;
```
would previously be stores as two separate declarations as if they had been declared like this:
```vhdl
signal a: std_logic;
signal b: std_logic;
```
Now, the AST element contains both identifiers.
This change is mostly for internal purposes. The only noticeable change is that hovers will now produce the former version, instead of the latter where applicable.
> AST normalization: store multiple identifiers per declaration instead of multiplying the declaration

- vhdl_lang/src/analysis/concurrent.rs
- vhdl_lang/src/analysis/declarative.rs
- vhdl_lang/src/analysis/range.rs
- vhdl_lang/src/analysis/scope.rs
- vhdl_lang/src/analysis/sequential.rs
- vhdl_lang/src/analysis/standard.rs
- vhdl_lang/src/analysis/tests/association_formal.rs
- vhdl_lang/src/analysis/tests/subprogram_instance.rs
- vhdl_lang/src/analysis/tests/tool_directive.rs
- vhdl_lang/src/analysis/tests/view_declarations.rs
- vhdl_lang/src/named_entity.rs
Closes #325 
Now analyses arrays of views, i.e.,
```vhdl
some_interface: view (some_view) of some_array_type
```
correctly.
This also handles the special case where no array is given, i.e.,
```vhdl
some_interface: view (some_view)
```
> Enable arrays of views

- vhdl_lang/src/analysis/names.rs
- vhdl_lang/src/analysis/tests/resolves_names.rs
- vhdl_lang/src/syntax/tokens/tokenizer.rs
- vhdl_lang/src/syntax/tokens/tokenstream.rs
> Resolve selected names of types

- vhdl_lang/src/analysis/static_expression.rs
> Allow underscores in decimal bit strings

- vhdl_lang/src/analysis/names.rs
- vhdl_lang/src/analysis/target.rs
- vhdl_lang/src/analysis/tests/assignment_typecheck.rs
- vhdl_lang/src/named_entity.rs
Closes #335 
Refactor the way signal attributes such as `x'delayed` or `x'quiet` are handled. This consequently correctly handles them in sensitivity lists.
> Refactor name analysis for signal attributes

- vhdl_ls/src/main.rs
- vhdl_ls/src/vhdl_server.rs
Introduces a flag so `vhdl_ls` can be called using `vhdl_ls --libararies /path/to/libraries`
Closes #339
> Add option for the libraries location as part of the vhdl_lang executable

- vhdl_lang/src/ast/search.rs
- vhdl_lang/src/ast/util.rs
- vhdl_lang/src/data/error_codes.rs
- vhdl_lang/src/lint.rs
- vhdl_lang/src/lint/sensitivity_list.rs
- vhdl_lang/src/main.rs
- vhdl_lang/src/named_entity.rs
- vhdl_lang/src/named_entity/object.rs
- vhdl_lang/src/project.rs
- vhdl_lang/tests/integration_tests.rs
- vhdl_ls/src/vhdl_server/lifecycle.rs
Closes #359 
Add a linter for sensitivity lists.
For the most part, the linter is designed to be conservative concerning error codes and only emit warnings when absolutely certain. This means that a couple of potential problems will not be raised.
- `missing_in_sensitivity_list` (default: warning): warns when there is a signal missing in the sensitivity list of a process that is read in a combinational process.
- `superfluous_in_sensitivity_list` (default: warning): warns when there is a signal in the sensitivity list of a process that is not read inside the process
The linting only applies to combinational processes. To differentiate whether a process is combinational or sequential, a heuristic is applied.
Every process that contains any numbers of `if` statements with conditions that …
> Lint sensitivity lists

- Cargo.lock
- Cargo.toml
- vhdl_lang/Cargo.toml
- vhdl_lang_macros/Cargo.toml
- vhdl_ls/Cargo.toml
Minimum supported rustc version (MSRV) was not provided. Also, it is more convenient to have shared info in the workspace Cargo.toml.
MSRV is 1.82 for the library (because of `iter::repeat_n`), but the use of brunch 0.9 require 1.85. As this is a test dependency, I decided to downgrade to 0.8 to keep MSRV a bit lower than the latest. Updating to 1.85 is now easier as that will also require updating to edition to 2024, which can be done in a single location.
In general, specifying version with "0" is a source for issues since it is OK to have breaking API changes for minor versions if major version is "0". For major version 1 and higher, there should be no breaking API changes without changing major version. I didn't specify a version for the crates that has "0" though (except for brunch …
> Move information to workspace and specify MSRV

- vhdl_lang/src/analysis/concurrent.rs
- vhdl_lang/src/analysis/declarative.rs
- vhdl_lang/src/analysis/names.rs
- vhdl_lang/src/analysis/package_instance.rs
- vhdl_lang/src/analysis/scope.rs
- vhdl_lang/src/analysis/sequential.rs
- vhdl_lang/src/analysis/tests/external_names.rs
- vhdl_lang/src/analysis/tests/mod.rs
- vhdl_lang/src/ast.rs
- vhdl_lang/src/completion.rs
- vhdl_lang/src/completion/libraries.rs
- vhdl_lang/src/completion/selected.rs
- vhdl_lang/src/data/error_codes.rs
- vhdl_lang/src/lint/dead_code.rs
- vhdl_lang/src/named_entity.rs
- vhdl_ls/src/vhdl_server.rs
- vhdl_ls/src/vhdl_server/completion.rs
Relates to #258 
Currently, we do not analyse external names at all. This adds a baseline implementation for package pathnames (i.e., `@lib.foo.bar`) in addition to type and kind checking in general.
> Add baseline analysis and completions for simple external names

- .github/workflows/build-test-all.yml
- .github/workflows/crates-io.yml
- .github/workflows/docker.yml
- Cargo.lock
- vhdl_lang/Cargo.toml
See https://blog.rafaelgss.dev/why-you-should-pin-actions-by-commit-hash for motivation why this is the safer way to handle action versions.
Also update the brunch depedency version.
One may consider activating the dependabot action, see https://github.com/apytypes/apytypes/blob/main/.github/dependabot.yml for an example (although one may consider checking weekly rather than monthly). This will create a PR to update the versions/hashes to the latest version when a new one is available.
> CI: Use hashes for GitHub actions

- vhdl_lang/src/config.rs
- vhdl_lang/src/lib.rs
- vhdl_ls/src/vhdl_server.rs
- vhdl_ls/src/vhdl_server/completion.rs
- vhdl_ls/src/vhdl_server/lifecycle.rs
- vhdl_ls/src/vhdl_server/workspace.rs
> Add support for customizable case transformation in completions
